server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    resolver 8.8.8.8 valid=30s;

    location /api/ {
        proxy_pass https://test1-production-6593.up.railway.app/api/;
        proxy_http_version 1.1;
        proxy_set_header Host test1-production-6593.up.railway.app;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_ssl_server_name on;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
